# Generated by Django 2.2 on 2019-04-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_price_in', models.FloatField()),
                ('goods_price_out', models.FloatField()),
                ('goods_desc', models.CharField(max_length=10000)),
                ('goods_address', models.CharField(max_length=1000)),
                ('goods_photo', models.CharField(max_length=1000)),
                ('goods_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Categories')),
            ],
        ),
    ]
